<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New School Registration Request</title>
    <style>
        body { margin: 0; padding: 0; background-color: #f4f6fb; font-family: 'Segoe UI', Arial, sans-serif; }
        .wrapper { max-width: 600px; margin: 40px auto; background: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 24px rgba(0,0,0,0.07); }
        .header { background: linear-gradient(135deg, #0947ca 0%, #031a61 100%); padding: 36px 40px; text-align: center; color: #ffffff; }
        .header h1 { font-size: 22px; font-weight: 700; margin: 0 0 6px; }
        .header p { color: rgba(255,255,255,0.85); font-size: 14px; margin: 0; }
        .body { padding: 40px; }
        .greeting { font-size: 18px; font-weight: 700; color: #0f172a; margin-bottom: 16px; }
        .text { font-size: 15px; color: #475569; line-height: 1.7; margin-bottom: 20px; }
        .info-table { width: 100%; border-collapse: collapse; margin: 20px 0; background: #f8fafc; border-radius: 10px; overflow: hidden; }
        .info-table th, .info-table td { padding: 12px 16px; font-size: 14px; text-align: left; border-bottom: 1px solid #e2e8f0; }
        .info-table th { background: #eff6ff; color: #1e3a8a; font-weight: 700; width: 35%; }
        .info-table td { color: #334155; }
        .footer { background: #f8fafc; padding: 24px 40px; text-align: center; }
        .footer p { font-size: 12px; color: #94a3b8; margin: 0; }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="header">
            <h1>🏫 New School Registration Request</h1>
            <p>EducoreERP System Notification</p>
        </div>

        <div class="body">
            <p class="greeting">Hello SuperAdmin,</p>
            <p class="text">
                A new school signup request has been submitted on <strong>EducoreERP</strong>. Please review the details below:
            </p>

            <table class="info-table">
                <tr>
                    <th>School Name</th>
                    <td><strong>{{ $schoolRequest->name }}</strong></td>
                </tr>
                <tr>
                    <th>Director/Admin</th>
                    <td>{{ $schoolRequest->director_name }}</td>
                </tr>
                <tr>
                    <th>School Type</th>
                    <td>{{ $schoolRequest->school_type }}</td>
                </tr>
                <tr>
                    <th>Email Address</th>
                    <td><a href="mailto:{{ $schoolRequest->email }}" style="color:#0947ca;">{{ $schoolRequest->email }}</a></td>
                </tr>
                <tr>
                    <th>Phone</th>
                    <td>{{ $schoolRequest->phone ?? 'N/A' }}</td>
                </tr>
                <tr>
                    <th>Address</th>
                    <td>{{ $schoolRequest->address }}</td>
                </tr>
                <tr>
                    <th>Request Code</th>
                    <td><code>{{ $schoolRequest->code }}</code></td>
                </tr>
                <tr>
                    <th>Submitted On</th>
                    <td>{{ $schoolRequest->created_at->format('d M Y, h:i A') }}</td>
                </tr>
            </table>

            <p class="text" style="margin-top:25px;">
                You can review, approve, or reject this request from your Superadmin Dashboard under <strong>School Requests</strong>.
            </p>
        </div>

        <div class="footer">
            <p>Automated notification generated by EducoreERP System.</p>
        </div>
    </div>
</body>
</html>
